services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapimongo_app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    command: poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload 

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
